version: '3.8'
services:
  openclaw:
    build: .
    container_name: openclaw
    ports:
      - '18789:18789'
    volumes:
      - 'openclaw_data:/data/openclaw'
    restart: unless-stopped
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENCLAW_GATEWAY_KEY=${OPENCLAW_GATEWAY_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
volumes:
  openclaw_data:
    name: openclaw_data
